// This file was extracted from original Barotrauma source code.
// Does not affected by own licence source.

using Barotrauma.Extensions;
using Microsoft.Xna.Framework;
using Barotrauma;

#pragma warning disable IDE0079
#pragma warning disable IDE0130
#pragma warning disable IDE0290

namespace MoreModTags
{
    abstract partial class TaggerMenu
    {
        protected static RectTransform NewItemRectT(GUILayoutGroup parent, float heightScale = 1.0f)
            => new((1.0f, 0.06f * heightScale), parent.RectTransform, Anchor.CenterLeft);

        protected static void Spacer(GUILayoutGroup parent, float height = 0.03f)
        {
            _ = new GUIFrame(new RectTransform((1.0f, height), parent.RectTransform, Anchor.CenterLeft), style: null);
        }

        protected static GUITextBlock Label(GUILayoutGroup parent, LocalizedString str, GUIFont font, float heightScale = 1.0f)
        {
            return new GUITextBlock(NewItemRectT(parent, heightScale), str, font: font);
        }

        public static GUITextBox ScrollableTextBox(GUILayoutGroup parent, float heightScale, string text)
        {
            var containingListBox = new GUIListBox(NewItemRectT(parent, heightScale));
            var textBox = new GUITextBox(
                new RectTransform(Vector2.One, containingListBox.Content.RectTransform),
                "", style: "GUITextBoxNoBorder", wrap: true,
                textAlignment: Alignment.TopLeft);
            textBox.OnTextChanged += (textBox, text) =>
            {
                string wrappedText = textBox.TextBlock.WrappedText.Value;
                int measuredHeight = (int)textBox.Font.MeasureString(wrappedText).Y;
                textBox.RectTransform.NonScaledSize =
                    (containingListBox.Content.Rect.Width,
                        Math.Max(measuredHeight, containingListBox.Content.Rect.Height));
                containingListBox.UpdateScrollBarSize();

                return true;
            };
            textBox.OnEnterPressed += (textBox, text) =>
            {
                string str = textBox.Text;
                int cursorPos = textBox.CaretIndex;
                textBox.Text = $"{str[..cursorPos]}\n{str[cursorPos..]}";
                textBox.CaretIndex = cursorPos + 1;

                return true;
            };
            textBox.Text = text;
            return textBox;
        }

        protected static GUIDropDown DropdownEnum<T>(
            GUILayoutGroup parent, Func<T, LocalizedString> textFunc, T currentValue,
            Action<T> setter) where T : Enum
            => Dropdown(parent, textFunc, (T[])Enum.GetValues(typeof(T)), currentValue, setter);

        protected static GUIDropDown Dropdown<T>(
            GUILayoutGroup parent, Func<T, LocalizedString> textFunc, IReadOnlyList<T> values, T currentValue,
            Action<T> setter, float heightScale = 1.0f)
        {
            var dropdown = new GUIDropDown(NewItemRectT(parent, heightScale));
            SwapDropdownValues(dropdown, textFunc, values, currentValue, setter);
            return dropdown;
        }

        protected static void SwapDropdownValues<T>(
            GUIDropDown dropdown,
            Func<T, LocalizedString> textFunc,
            IReadOnlyList<T> values,
            T currentValue,
            Action<T> setter)
        {
            if (dropdown.ListBox.Content.Children.Any(c => c.UserData is not T))
            {
                throw new Exception("SwapValues must preserve the type of the dropdown's userdata");
            }

            dropdown.OnSelected = null;
            dropdown.ClearChildren();

            values.ForEach(v => dropdown.AddItem(text: textFunc(v), userData: v));
            dropdown.Select(values.IndexOf(currentValue));
            dropdown.OnSelected = (dd, obj) =>
            {
                setter((T)obj);
                return true;
            };
        }

        protected static int Round(float v) => (int)MathF.Round(v);
        protected static string Percentage(float v) => $"{Round(v * 100)}";
    }


    // This Class has been generated by AI.
    public static class RichStringExt
    {
        public static string SetColor(this string text, string colorName)
        => $"‖color:{colorName}‖{text}‖end‖";

        public static string SetColor(this string text, Color color)
            => $"‖color:{color.R},{color.G},{color.B}‖{text}‖end‖";

        public static string SetColorHex(this string text, string hexCode)
            => $"‖color:{hexCode}‖{text}‖end‖";

        public static string SetBold(this string text)
            => $"‖bold‖{text}‖end‖";

        public static string SetItalic(this string text)
            => $"‖italic‖{text}‖end‖";

        public static string SetUnderline(this string text)
            => $"‖underline‖{text}‖end‖";

        public static string SetStrikethrough(this string text)
            => $"‖strikethrough‖{text}‖end‖";

        public static LocalizedString SetColor(this LocalizedString text, string colorName)
        => $"‖color:{colorName}‖{text}‖end‖";

        public static LocalizedString SetColor(this LocalizedString text, Color color)
            => $"‖color:{color.R},{color.G},{color.B}‖{text}‖end‖";

        public static LocalizedString SetColorHex(this LocalizedString text, string hexCode)
            => $"‖color:{hexCode}‖{text}‖end‖";

        public static LocalizedString SetBold(this LocalizedString text)
            => $"‖bold‖{text}‖end‖";

        public static LocalizedString SetItalic(this LocalizedString text)
            => $"‖italic‖{text}‖end‖";

        public static LocalizedString SetUnderline(this LocalizedString text)
            => $"‖underline‖{text}‖end‖";

        public static LocalizedString SetStrikethrough(this LocalizedString text)
            => $"‖strikethrough‖{text}‖end‖";

    }
}
